name: "TheCleanArch CI/CD"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: |
          dotnet tool restore
          dotnet restore ./TheCleanArch.sln

      - name: Build
        run: dotnet build ./TheCleanArch.sln -c Release --no-restore

      - name: Test
        run: dotnet test ./TheCleanArch.sln -c Release --no-build

      - run: dotnet gitversion
      - run: dotnet gitversion /output json /showvariable BuildMetaData
      - run: dotnet gitversion /output json /showvariable SemVer
      - run: dotnet gitversion /output json /showvariable FullSemVer
      - run: dotnet gitversion /output json /showvariable ShortSha
      - run: dotnet gitversion /output json /showvariable NuGetVersionV2
      - run: dotnet gitversion /output json /showvariable CommitsSinceVersionSource

      - run: |
          build_meta_data=$(dotnet gitversion /output json /showvariable BuildMetaData)
          if [ "$build_meta_data" == "" ]; then
            echo "BuildMetaData é nulo!"
          else
            echo "BuildMetaData não nulo!"
          fi
