name: "TheCleanArch CI/CD"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
      steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Setup dotNET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: .NET Restore
        run: dotnet restore ./TheCleanArch.sln

      - name: .NET Build
        run: dotnet build ./TheCleanArch.sln -c Release --no-restore

      - name: .NET Test
        run: dotnet test ./TheCleanArch.sln -c Release --no-build