name: "TheCleanArch CI/CD"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true
          additionalArguments: '/showConfig'

      - run: env

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore ./TheCleanArch.sln

      - name: Build
        run: dotnet build ./TheCleanArch.sln -c Release --no-restore

      - name: Test
        run: dotnet test ./TheCleanArch.sln -c Release --no-build

      - run: echo ${{ steps.version_step.outputs.fullSemVer }}
