name: dotNET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup dotNET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: |
        dotnet restore ./src/CleanArch.Core/CleanArch.Core.csproj
        dotnet restore ./src/CleanArch.DomainDrivenDesign/CleanArch.DomainDrivenDesign.csproj
        dotnet restore ./test/CleanArch.Core.Tests/CleanArch.Core.Tests.csproj
        dotnet restore ./test/CleanArch.DomainDrivenDesign.Tests/CleanArch.DomainDrivenDesign.Tests.csproj
    
    - name: Build
      run: |
        dotnet build ./src/CleanArch.Core/CleanArch.Core.csproj --configuration Release --no-restore
        dotnet build ./src/CleanArch.DomainDrivenDesign/CleanArch.DomainDrivenDesign.csproj --configuration Release --no-restore
        dotnet build ./test/CleanArch.Core.Tests/CleanArch.Core.Tests.csproj --configuration Release --no-restore
        dotnet build ./test/CleanArch.DomainDrivenDesign.Tests/CleanArch.DomainDrivenDesign.Tests.csproj --configuration Release --no-restore
    
    - name: Test
      run: |
        dotnet test ./test/CleanArch.Core.Tests/CleanArch.Core.Tests.csproj --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
        dotnet test ./test/CleanArch.DomainDrivenDesign.Tests/CleanArch.DomainDrivenDesign.Tests.csproj --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
