on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: .NET Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output ./artifacts
    - name: .NET Push
      run: dotnet nuget push ./artifacts/CleanArch.*.${VERSION}.nupkg --source https://nuget.pkg.github.com/e5r/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}